[tool.poetry]
name = "tokenserver"
version = "0.1.0"
description = "Tokenserver Utilities."
authors = ["Mozilla Services Engineering <services-engineering+code@mozilla.com>"]
license = "Mozilla Public License Version 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto = "==2.49"
datadog = "^0.49.1"
backoff = "^2.2.1"
hawkauthlib = "==2.0.0"
mysqlclient = "^2.1.1"
pyramid = "==2.0.2"
sqlalchemy = "==1.4.46"
tokenlib = "==2.0.0"
PyBrowserID = "==0.14.0"
testfixtures = "^8.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
