[tool.poetry]
name = "loadtests"
version = "0.1.0"
description = "Tokenserver Load Tests"
authors = ["Mozilla Services Engineering <services-engineering+code@mozilla.com>"]
license = "Mozilla Public License Version 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Authlib = "^1.3.1"
cryptography = "^42.0.8"
locust = "^2.29.1"
PyBrowserID = "^0.14.0"
PyJWT = "^2.8.0"
SQLAlchemy = "^2.0.31"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
